
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[329] =
    {   0,
       63,   63,   68,   65,    2,   66,    2,   65,   65,    1,
       61,   64,   60,   64,   63,   57,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   67,   67,   65,   56,   65,    0,   58,    1,
        1,   64,   64,   65,   64,   63,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   64,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,    0,   58,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   45,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,    9,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,    0,   59,   65,   65,   65,   65,
       21,   41,   65,   65,   24,   65,   65,   65,   65,   65,
       65,   65,   14,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   50,   65,   65,   65,   65,
       65,    0,   65,   42,   52,   65,   65,   65,   65,   65,
       65,   30,   49,   65,   65,   65,   65,   65,   65,    8,

       16,   13,   12,   65,   65,   65,   65,   65,   65,   65,
       65,    4,   65,   29,   65,   65,   65,   65,   28,   65,
        3,   65,   65,   65,   62,   11,   65,   65,   65,   65,
       65,   65,   65,   65,   47,   65,   43,   34,   17,   65,
       18,   65,   65,   65,   40,   65,   65,   65,   65,    7,
       46,   65,   65,   65,   65,   53,   65,   23,   65,   65,
       65,   65,   65,   65,   48,   20,   65,   65,   65,   32,
       65,   65,   65,   65,   65,   65,   33,   44,   37,   65,
       65,   65,   55,   65,   65,   15,   39,   65,   26,   65,
       65,   65,   65,   35,   65,   65,   65,   65,   31,   51,

       65,   65,   65,   65,   65,   25,   65,   65,   36,   22,
       10,   27,   65,   65,   65,   65,   65,   54,   65,    5,
       65,    6,   19,   65,   65,   65,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    1,    1,    1,
        1,    8,    9,    1,   10,   11,    1,   12,   13,   14,
       15,   16,   16,   16,   16,   16,   16,   17,    1,    1,
       18,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
        1,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,    1,   44,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,    1,   55,   56,   57,   58,
       59,   60,    1,   61,   62,   63,   64,   65,   66,   67,
       68,   69,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[335] =
    {   0,
        0,    0,  244,    0,  771,  771,    0,  224,   68,   70,
      771,   68,   74,   80,   93,    0,   81,   37,   85,  104,
      150,   44,   80,   70,  148,  150,  154,   76,  102,  195,
      165,  227,    0,  771,    0,    0,  133,  223,  218,  191,
        0,  224,  240,  255,  263,  269,  281,   84,   94,  122,
      242,  129,  138,  148,  195,  289,  294,  155,  168,  250,
      251,  253,  271,  258,  282,  295,  284,  300,  296,  291,
      298,  305,  304,  305,  309,  303,  296,  300,  300,  314,
      310,  313,  316,  309,  306,  325,  184,  221,  332,  339,
      335,  347,  342,  338,  358,  345,  357,  346,  354,  180,

      158,    0,  348,  353,  362,  355,  360,  355,  358,  368,
      372,  359,  364,  374,  367,  366,  146,  373,  388,  385,
      394,  392,  394,  394,  412,  396,  411,  411,  403,  414,
      409,  406,  407,  411,  172,    0,  404,  417,  408,  411,
        0,    0,  421,  418,    0,  112,  414,  430,  427,  418,
      448,  441,    0,  438,  447,  449,  455,  455,  460,  454,
      455,  454,  468,  465,  460,  465,  470,  461,  464,  476,
      467,  467,  472,  484,  471,    0,  473,  491,  493,  494,
      503,  524,  519,    0,    0,  520,  513,  111,  508,  520,
      515,    0,    0,  514,  525,  520,  528,  519,  512,    0,

        0,    0,    0,  536,  527,  523,  540,  527,  530,  530,
      537,    0,  538,    0,  110,  545,  533,  532,  545,  555,
        0,  555,  564,  573,  586,    0,  568,  579,  569,  571,
      573,  579,  592,  593,  140,  579,    0,    0,    0,  588,
        0,  594,  583,  585,    0,  595,  599,  600,  596,    0,
        0,  584,  584,  594,  595,    0,  594,    0,  609,  617,
      618,  626,  622,  636,    0,    0,  622,  624,  637,    0,
      625,  628,  628,   95,  633,  644,    0,    0,   93,  635,
      645,  636,    0,  637,  650,    0,    0,  641,  124,   88,
      639,  654,  656,    0,  644,  658,  659,  657,    0,    0,

      654,  120,  654,  663,  677,    0,  671,  676,    0,    0,
        0,    0,   62,  688,  679,  687,  689,    0,  694,    0,
      686,    0,    0,  691,  698,  688,    0,  771,   74,  750,
      754,  758,  762,  766
    } ;

static const flex_int16_t yy_def[335] =
    {   0,
      328,    1,  328,  329,  328,  328,  329,  329,  330,  331,
      328,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  332,  328,  329,  329,  330,  333,  330,  331,
      334,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  332,  333,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  328,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  328,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  328,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,    0,  328,  328,
      328,  328,  328,  328
    } ;

static const flex_int16_t yy_nxt[841] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   15,   15,   15,   15,    4,   16,   17,   18,
       19,   20,   21,   22,   23,    4,   24,    4,    4,   25,
       26,   27,   28,   29,   30,   31,    4,    4,    4,   32,
        4,    4,   33,   34,    4,   17,   18,   19,   20,   21,
       22,   23,    4,   24,    4,    4,   25,   26,   27,   28,
       29,   30,   31,    4,    4,    4,   32,    4,    4,   38,
       50,   41,   60,   39,   35,   38,  318,   41,   42,   43,
       43,   43,   43,   43,   42,   43,   43,   43,   43,   43,
       44,   45,   45,   45,   45,   45,   44,   50,   61,   60,

       62,   48,   44,   42,   46,   46,   46,   46,   46,   76,
       38,   38,   41,   41,   49,   44,   51,   44,   47,   90,
       91,   52,   53,   44,   77,   61,   54,   62,   48,   44,
       55,  312,  303,   78,   38,  302,   76,  295,   39,  292,
       38,   49,   44,   51,   92,   47,   90,   91,   52,   53,
       95,   77,  265,   54,  248,  229,  189,   55,   56,   56,
       78,   57,   57,   57,   57,   57,   63,   96,   68,   64,
       65,   92,   97,   58,   72,   38,   38,   95,  101,   66,
       59,   69,   67,   70,   73,   71,   74,   75,  182,  102,
      164,   83,   41,   63,   96,   68,   64,   65,   41,   97,

       58,   72,  148,   84,   85,  101,   66,   59,   69,   67,
       70,   73,   71,   74,   75,   79,  102,   80,   83,   38,
       81,   98,   82,   39,  147,   38,   88,  135,   88,   99,
       84,   85,  100,   41,   41,   45,   45,   45,   45,   45,
       86,   36,   79,  328,   80,  328,   44,   81,   98,   82,
       42,   43,   43,   43,   43,   43,   99,  328,  328,  100,
       38,   38,   44,   56,   56,  328,   57,   57,   57,   57,
       57,   93,   94,   44,   45,   45,   45,   45,   45,   42,
       46,   46,   46,   46,   46,   44,  103,  104,  105,   44,
      108,   44,   89,   89,   89,   89,   89,  106,   93,   94,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
      107,  109,   44,  103,  104,  105,  110,  108,   44,  111,
      112,  114,  115,  116,  106,  117,  118,  119,  120,  121,
      122,  124,  123,  125,  126,  113,  128,  107,  109,  129,
      132,  133,  127,  110,  130,  134,  111,  112,  114,  115,
      116,  131,  117,  118,  119,  120,  121,  122,  124,  123,
      125,  126,  113,  128,  136,  137,  129,  132,  133,  127,
      138,  130,  134,  139,  140,  141,  142,  143,  131,  144,
      145,  146,  149,  150,  151,  153,  154,  152,  155,  156,
      157,  136,  137,  158,  159,  160,  161,  138,  162,  163,

      139,  140,  141,  142,  143,  165,  144,  145,  146,  149,
      150,  151,  153,  154,  152,  155,  156,  157,  166,  167,
      158,  159,  160,  161,  168,  162,  163,  169,  170,  171,
      172,  173,  165,  174,  175,  176,  177,  178,  179,  180,
      181,  183,  184,  185,  186,  166,  167,  187,  188,  190,
      191,  168,  192,  193,  169,  170,  171,  172,  173,  196,
      174,  175,  176,  177,  178,  179,  180,  181,  183,  184,
      185,  186,  194,  197,  187,  188,  190,  191,  198,  192,
      193,  195,  199,  200,  201,  202,  196,  204,  205,  206,
      207,  208,  203,  209,  210,  211,  212,  213,  214,  194,

      197,  215,  216,  217,  218,  198,  219,  220,  195,  199,
      200,  201,  202,  221,  204,  205,  206,  207,  208,  203,
      209,  210,  211,  212,  213,  214,  222,  223,  215,  216,
      217,  218,  224,  219,  220,  225,  225,  225,  225,  225,
      221,  226,  227,  228,  230,  231,  232,  233,  234,  235,
      236,  237,  238,  222,  223,  239,  240,  241,  242,  224,
      243,  244,  245,  246,  247,  249,  250,  251,  226,  227,
      228,  230,  231,  232,  233,  234,  235,  236,  237,  238,
      252,  253,  239,  240,  241,  242,  254,  243,  244,  245,
      246,  247,  249,  250,  251,  255,  256,  225,  225,  225,

      225,  225,  257,  258,  259,  260,  261,  252,  253,  262,
      263,  264,  266,  254,  267,  268,  269,  270,  271,  272,
      273,  274,  255,  256,  275,  276,  277,  278,  279,  257,
      258,  259,  260,  261,  280,  281,  262,  263,  264,  266,
      282,  267,  268,  269,  270,  271,  272,  273,  274,  283,
      284,  275,  276,  277,  278,  279,  285,  286,  287,  288,
      289,  280,  281,  290,  291,  293,  294,  282,  296,  297,
      298,  299,  300,  301,  304,  305,  283,  284,  306,  307,
      308,  309,  310,  285,  286,  287,  288,  289,  311,  313,
      290,  291,  293,  294,  314,  296,  297,  298,  299,  300,

      301,  304,  305,  315,  316,  306,  307,  308,  309,  310,
      317,  319,  320,  321,  322,  311,  313,  323,  324,  325,
      326,  314,  327,  328,  328,  328,  328,  328,  328,  328,
      315,  316,  328,  328,  328,  328,  328,  317,  319,  320,
      321,  322,  328,  328,  323,  324,  325,  326,  328,  327,
       37,   37,  328,   37,   40,   40,  328,   40,   87,  328,
      328,   87,   38,   38,  328,   38,   41,   41,  328,   41,
        3,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_chk[841] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
       18,   10,   22,    9,  329,    9,  313,   10,   12,   12,
       12,   12,   12,   12,   13,   13,   13,   13,   13,   13,
       12,   14,   14,   14,   14,   14,   13,   18,   23,   22,

       24,   17,   14,   15,   15,   15,   15,   15,   15,   28,
        9,    9,   10,   10,   17,   15,   19,   12,   15,   48,
       49,   19,   20,   13,   29,   23,   20,   24,   17,   14,
       20,  302,  290,   29,   37,  289,   28,  279,   37,  274,
       37,   17,   15,   19,   50,   15,   48,   49,   19,   20,
       52,   29,  235,   20,  215,  188,  146,   20,   21,   21,
       29,   21,   21,   21,   21,   21,   25,   53,   26,   25,
       25,   50,   54,   21,   27,   37,   37,   52,   58,   25,
       21,   26,   25,   26,   27,   26,   27,   27,  135,   59,
      117,   31,   40,   25,   53,   26,   25,   25,   40,   54,

       21,   27,  101,   31,   31,   58,   25,   21,   26,   25,
       26,   27,   26,   27,   27,   30,   59,   30,   31,   39,
       30,   55,   30,   39,  100,   39,   88,   87,   38,   55,
       31,   31,   55,   40,   40,   42,   42,   42,   42,   42,
       32,    8,   30,    3,   30,    0,   42,   30,   55,   30,
       43,   43,   43,   43,   43,   43,   55,    0,    0,   55,
       39,   39,   43,   44,   44,    0,   44,   44,   44,   44,
       44,   51,   51,   42,   45,   45,   45,   45,   45,   46,
       46,   46,   46,   46,   46,   45,   60,   61,   62,   43,
       64,   46,   47,   47,   47,   47,   47,   63,   51,   51,

       56,   56,   56,   56,   56,   57,   57,   57,   57,   57,
       63,   65,   45,   60,   61,   62,   66,   64,   46,   67,
       68,   69,   70,   71,   63,   72,   73,   74,   75,   76,
       77,   78,   77,   79,   80,   68,   81,   63,   65,   82,
       84,   85,   80,   66,   83,   86,   67,   68,   69,   70,
       71,   83,   72,   73,   74,   75,   76,   77,   78,   77,
       79,   80,   68,   81,   89,   90,   82,   84,   85,   80,
       91,   83,   86,   92,   93,   94,   95,   96,   83,   97,
       98,   99,  103,  104,  105,  106,  107,  105,  108,  109,
      110,   89,   90,  111,  112,  113,  114,   91,  115,  116,

       92,   93,   94,   95,   96,  118,   97,   98,   99,  103,
      104,  105,  106,  107,  105,  108,  109,  110,  119,  120,
      111,  112,  113,  114,  121,  115,  116,  122,  123,  124,
      125,  126,  118,  127,  128,  129,  130,  131,  132,  133,
      134,  137,  138,  139,  140,  119,  120,  143,  144,  147,
      148,  121,  149,  150,  122,  123,  124,  125,  126,  152,
      127,  128,  129,  130,  131,  132,  133,  134,  137,  138,
      139,  140,  151,  154,  143,  144,  147,  148,  155,  149,
      150,  151,  156,  157,  158,  159,  152,  160,  161,  162,
      163,  164,  159,  165,  166,  167,  168,  169,  170,  151,

      154,  171,  172,  173,  174,  155,  175,  177,  151,  156,
      157,  158,  159,  178,  160,  161,  162,  163,  164,  159,
      165,  166,  167,  168,  169,  170,  179,  180,  171,  172,
      173,  174,  181,  175,  177,  182,  182,  182,  182,  182,
      178,  183,  186,  187,  189,  190,  191,  194,  195,  196,
      197,  198,  199,  179,  180,  204,  205,  206,  207,  181,
      208,  209,  210,  211,  213,  216,  217,  218,  183,  186,
      187,  189,  190,  191,  194,  195,  196,  197,  198,  199,
      219,  220,  204,  205,  206,  207,  222,  208,  209,  210,
      211,  213,  216,  217,  218,  223,  224,  225,  225,  225,

      225,  225,  227,  228,  229,  230,  231,  219,  220,  232,
      233,  234,  236,  222,  240,  242,  243,  244,  246,  247,
      248,  249,  223,  224,  252,  253,  254,  255,  257,  227,
      228,  229,  230,  231,  259,  260,  232,  233,  234,  236,
      261,  240,  242,  243,  244,  246,  247,  248,  249,  262,
      263,  252,  253,  254,  255,  257,  264,  267,  268,  269,
      271,  259,  260,  272,  273,  275,  276,  261,  280,  281,
      282,  284,  285,  288,  291,  292,  262,  263,  293,  295,
      296,  297,  298,  264,  267,  268,  269,  271,  301,  303,
      272,  273,  275,  276,  304,  280,  281,  282,  284,  285,

      288,  291,  292,  305,  307,  293,  295,  296,  297,  298,
      308,  314,  315,  316,  317,  301,  303,  319,  321,  324,
      325,  304,  326,    0,    0,    0,    0,    0,    0,    0,
      305,  307,    0,    0,    0,    0,    0,  308,  314,  315,
      316,  317,    0,    0,  319,  321,  324,  325,    0,  326,
      330,  330,    0,  330,  331,  331,    0,  331,  332,    0,
        0,  332,  333,  333,    0,  333,  334,  334,    0,  334,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "expt.l"
/*
 *  EXP-T -- A Relativistic Fock-Space Multireference Coupled Cluster Program
 *  Copyright (C) 2018-2020 The EXP-T developers.
 *
 *  This file is part of EXP-T.
 *
 *  EXP-T is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  EXP-T is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with EXP-T.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  E-mail:        exp-t-program@googlegroups.com
 *  Google Groups: https://groups.google.com/d/forum/exp-t-program
 */
#line 25 "expt.l"

#include "lexer.h"

#define MAX_TOKEN_LEN 1024

void inc_col();
int yycol = 0;
int prev_len = -1;

#line 767 "lex.yy.c"
#line 768 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "expt.l"

#line 987 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 771 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "expt.l"
{ inc_col(); } /* single-line comments beginning with '#' */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "expt.l"
{ inc_col(); } /* ignore whitespace */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "expt.l"
{ inc_col(); return KEYWORD_TITLE;        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "expt.l"
{ inc_col(); return KEYWORD_PRINT;        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "expt.l"
{ inc_col(); return KEYWORD_SCRATCH_DIR;  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "expt.l"
{ inc_col(); return KEYWORD_DEGEN_THRESH; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "expt.l"
{ inc_col(); return KEYWORD_SECTOR;       }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "expt.l"
{ inc_col(); return KEYWORD_MODEL;        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "expt.l"
{ inc_col(); return KEYWORD_OCC;          }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "expt.l"
{ inc_col(); return KEYWORD_OCC_IRREPS;   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "expt.l"
{ inc_col(); return KEYWORD_ACTIVE;       }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "expt.l"
{ inc_col(); return KEYWORD_NACTP;        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "expt.l"
{ inc_col(); return KEYWORD_NACTH;        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "expt.l"
{ inc_col(); return KEYWORD_MAIN;         }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "expt.l"
{ inc_col(); return KEYWORD_NOHERMIT;     }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "expt.l"
{ inc_col(); return KEYWORD_MSTDM;        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "expt.l"
{ inc_col(); return KEYWORD_NATORB;       }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "expt.l"
{ inc_col(); return KEYWORD_NROOTS;       }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "expt.l"
{ inc_col(); return KEYWORD_ROOTS_CUTOFF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "expt.l"
{ inc_col(); return KEYWORD_MAXITER;      }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "expt.l"
{ inc_col(); return KEYWORD_CONV;         }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "expt.l"
{ inc_col(); return KEYWORD_DIV_THRESH;   }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "expt.l"
{ inc_col(); return KEYWORD_DAMPING;      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "expt.l"
{ inc_col(); return KEYWORD_DIIS;         }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "expt.l"
{ inc_col(); return KEYWORD_SHIFTTYPE;    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "expt.l"
{ inc_col(); return KEYWORD_ORBSHIFT;     }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "expt.l"
{ inc_col(); return KEYWORD_ORBSHIFT00;   }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "expt.l"
{ inc_col(); return KEYWORD_SHIFT;        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "expt.l"
{ inc_col(); return KEYWORD_REUSE;        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "expt.l"
{ inc_col(); return KEYWORD_FLUSH;        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "expt.l"
{ inc_col(); return KEYWORD_INTEGRALS;    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "expt.l"
{ inc_col(); return KEYWORD_ONEPROP;      }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "expt.l"
{ inc_col(); return KEYWORD_TWOPROP;      }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "expt.l"
{ inc_col(); return KEYWORD_MEMORY;       }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "expt.l"
{ inc_col(); return KEYWORD_TILESIZE;     }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "expt.l"
{ inc_col(); return KEYWORD_DISK_USAGE;   }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "expt.l"
{ inc_col(); return KEYWORD_COMPRESS;     }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "expt.l"
{ inc_col(); return KEYWORD_COMPRESS_TRIPLES; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "expt.l"
{ inc_col(); return KEYWORD_NTHREADS;     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "expt.l"
{ inc_col(); return KEYWORD_OPENMP;       }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "expt.l"
{ inc_col(); return KEYWORD_CUDA;         }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "expt.l"
{ inc_col(); return KEYWORD_ARITH;        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "expt.l"
{ inc_col(); return KEYWORD_MDPROP;       }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "expt.l"
{ inc_col(); return KEYWORD_TXTPROP;      }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "expt.l"
{ inc_col(); return KEYWORD_END;          }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "expt.l"
{ inc_col(); return KEYWORD_SELECT;       }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "expt.l"
{ inc_col(); return KEYWORD_INTHAM;       }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "expt.l"
{ inc_col(); return KEYWORD_INTHAM1;      }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "expt.l"
{ inc_col(); return KEYWORD_GAUNT;        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "expt.l"
{ inc_col(); return KEYWORD_SKIP;         }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "expt.l"
{ inc_col(); return KEYWORD_INTERFACE;    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "expt.l"
{ inc_col(); return KEYWORD_BREIT;        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "expt.l"
{ inc_col(); return KEYWORD_X2CMMF;       }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "expt.l"
{ inc_col(); return KEYWORD_RESTRICT_T3;  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "expt.l"
{ inc_col(); return KEYWORD_EFF_CONF;     }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "expt.l"
{ inc_col(); return TT_NEQ;               }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "expt.l"
{ inc_col(); return TT_EQ;                }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "expt.l"
{ inc_col(); return TT_QUOTE;             }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "expt.l"
{ inc_col(); return TT_SECTOR;            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "expt.l"
{ inc_col(); return TT_HYPHEN;            }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "expt.l"
{ inc_col(); return TT_STAR;              }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "expt.l"
{ inc_col(); return TT_ELEC_STATE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "expt.l"
{ inc_col(); return TT_INTEGER;           }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "expt.l"
{ inc_col(); return TT_FLOAT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "expt.l"
{ inc_col(); return TT_WORD;     }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 104 "expt.l"
{ inc_col(); yylineno++; return END_OF_LINE; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 105 "expt.l"
{ return END_OF_FILE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "expt.l"
ECHO;
	YY_BREAK
#line 1384 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 328);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "expt.l"


/* just dummy */
int yywrap() {
   return 1;
}

/**
 * updates the number of the current column
 */
void inc_col()
{
    // update yycol
    if (prev_len == -1) {
        yycol = 0;
    }
    else {
        yycol += prev_len;
    }

    // update prev_len
    if (strcmp(yytext, "\n") == 0) {
        prev_len = -1;
    }
    else {
        prev_len = strlen(yytext);
    }
}


