
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[493] =
    {   0,
       80,   80,   85,   82,    2,   83,    2,   82,   82,    1,
       78,   81,   77,   81,   80,   74,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   84,   84,   82,   73,   82,
        0,   75,    1,    1,   81,   81,   82,   81,   80,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   81,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,    0,

       75,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   45,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,    9,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,    0,   76,
       82,   82,   82,   82,   82,   20,   24,   41,   82,   82,
       82,   23,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   82,   82,   82,   82,   50,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,    0,
       82,   82,   42,   52,   82,   82,   82,   82,   82,   82,
       29,   49,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,    8,   15,   13,   12,   82,   82,   82,
       82,   82,   82,   82,   82,    4,   82,   82,   28,   82,
       82,   82,   82,   27,   82,   82,   82,    3,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   79,   11,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   14,   82,
       82,   82,   82,   82,   60,   82,   43,   33,   16,   82,

       17,   82,   82,   82,   39,   82,   82,   82,   82,   82,
        7,   46,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   64,   82,   53,   82,   82,   22,   82,
       59,   82,   82,   82,   82,   82,   48,   82,   82,   47,
       19,   82,   82,   82,   31,   82,   61,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   70,   82,   82,
       32,   44,   82,   82,   36,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   38,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   34,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   72,   82,   30,   51,

       82,   82,   82,   65,   82,   82,   82,   25,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   35,   21,
       82,   82,   82,   10,   82,   82,   82,   82,   26,   82,
       82,   82,   82,   67,   82,   58,   82,   82,   82,   82,
       54,   82,   55,   82,    5,   82,   82,   82,   82,   66,
       82,    6,   82,   82,   82,   18,   82,   82,   82,   69,
       82,   82,   82,   82,   56,   71,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   68,   37,   82,
       82,   82,   40,   82,   82,   82,   82,   62,   63,   82,
       57,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    1,    1,    1,
        1,    8,    9,    1,   10,   11,    1,   12,   13,   14,
       15,   12,   12,   12,   12,   12,   12,   16,    1,    1,
       17,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
        1,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,    1,   43,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,    1,   54,   55,   56,   57,
       58,   59,    1,   60,   61,   62,   63,   64,   65,   66,
       67,   68,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[499] =
    {   0,
        0,    0, 1025,    0, 1036, 1036,    0, 1005,   67,   69,
     1036,   67,   72,   78,   92,    0,   68,   37,   87,  104,
      122,   44,  111,   97,  113,   95,  133,  140,  156,  106,
      141,  184,  179,  134, 1004,    0, 1036,    0,    0,  217,
     1005,  240,  219,    0,  241,  253,  264,  272,  284,  237,
      136,  162,  157,  175,  251,  177,  191,  201,  279,  267,
      257,  298,  267,  253,  255,  264,  267,  281,  963,  279,
      288,  283,  291,  295,  304,  291,  319,  291,  303,  310,
      317,  316,  318,  320,  317,  337,  314,  314,  335,  322,
      332,  333,  330,  348,  962,  337,  342,  356,  359,  962,

      998,  348,  362,  361,  356,  366,  361,  357,  364,  379,
      367,  379,  368,  374,  382,  959,    0,  377,  382,  392,
      385,  392,  396,  405,  406,  405,  399,  402,  412,  416,
      407,  412,  952,  414,  413,  951,  415,  418,  417,  421,
      435,  420,  422,  427,  445,  430,  444,  444,  436,  441,
      442,  457,  453,  467,  452,  453,  949,  457,  975,    0,
      454,  457,  474,  465,  469,    0,    0,    0,  478,  475,
      481,    0,  946,  474,  485,  481,  483,  493,  498,  492,
      506,  504,  504,  498,  504,  505,  512,  512,  526,  509,
      511,  515,  531,  528,  522,  527,  531,  526,  535,  531,

      548,  537,  538,  543,  555,  541,    0,  548,  553,  553,
      567,  567,  567,  558,  558,  563,  566,  573,  576,  615,
      585,  574,    0,    0,  588,  582,  302,  578,  579,  592,
      214,    0,  583,  589,  591,  604,  605,  618,  614,  628,
      625,  616,  609,    0,    0,    0,    0,  631,  622,  620,
      637,  623,  626,  626,  641,    0,  641,  636,    0,  203,
      643,  631,  631,  634,  634,  638,  646,    0,  648,  661,
      664,  674,  666,  669,  679,  667,  680,  695,    0,  196,
      670,  681,  676,  672,  679,  682,  698,  686,    0,  193,
      684,  702,  703,  221,    0,  690,    0,    0,    0,  692,

        0,  705,  700,  702,  185,  703,  182,  716,  717,  716,
        0,    0,  706,  714,  178,  152,  710,  726,  721,  721,
      148,  725,  726,    0,  143,    0,  727,  731,    0,  741,
        0,  749,  747,  741,  741,  745,    0,  746,  755,    0,
        0,  742,  745,  758,    0,  769,    0,  757,  754,  754,
      140,  759,  755,  772,  768,  783,  786,    0,  133,  774,
        0,    0,  790,  778,  130,  779,  789,  785,  788,  799,
      805,  790,  803,  800,    0,  796,  801,  809,  117,  798,
      813,  819,  810,  825,  811,    0,  811,  817,  823,  837,
      828,  827,  841,  842,  840,  838,    0,  839,    0,    0,

      843,  840,  851,    0,  842,  847,  853,    0,  858,  863,
      865,  858,  855,  860,  861,  864,  864,  864,    0,    0,
      873,  882,  884,    0,  880,  144,  890,  883,    0,  895,
      892,  879,  888,    0,  900,    0,  901,  903,  894,  900,
        0,  899,    0,  910,    0,  906,  906,  104,  905,    0,
      907,    0,  905,  909,  923,    0,  916,  917,  917,    0,
      925,  936,   80,  927,    0,    0,  934,  945,  948,   82,
      946,  944,  939,  940,  950,  956,  953,    0,    0,   64,
       88,   63,    0,  948,  953,  954,  948,    0,    0,  953,
        0, 1036,   73, 1015, 1019, 1023, 1027, 1031

    } ;

static const flex_int16_t yy_def[499] =
    {   0,
      492,    1,  492,  493,  492,  492,  493,  493,  494,  495,
      492,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  496,  492,  493,  493,  494,
      497,  494,  495,  498,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  496,

      497,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  492,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,

      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  492,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  492,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,

      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,

      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,    0,  492,  492,  492,  492,  492,  492

    } ;

static const flex_int16_t yy_nxt[1105] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   15,   15,   15,    4,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,    4,   26,   27,   28,
       29,   30,   31,   32,   33,   34,    4,    4,   35,    4,
        4,   36,   37,    4,   17,   18,   19,   20,   21,   22,
       23,   24,   25,    4,   26,   27,   28,   29,   30,   31,
       32,   33,   34,    4,    4,   35,    4,    4,   41,   54,
       44,   64,   42,   38,   41,  486,   44,   45,   46,   46,
       46,   46,   45,   46,   46,   46,   46,   51,   47,   48,
       48,   48,   48,   47,  475,  476,   54,   52,   64,   47,

       53,  485,   45,   49,   49,   49,   49,  484,   41,   41,
       44,   44,   71,   47,   51,   47,   50,   55,   67,   56,
       47,   58,   57,  470,   52,   59,   47,   53,   65,   60,
       61,   61,   68,   62,   62,   62,   62,   69,   85,   71,
       47,   66,   70,   50,   55,   67,   56,  459,   58,   57,
       72,   63,   59,   73,   74,   65,   60,   77,  443,   68,
      405,   78,   86,   75,   69,   85,   76,   98,   66,   70,
      103,   87,   79,  392,   80,   81,  388,   72,   63,  104,
       73,   74,  105,  381,   77,   82,  363,   83,   78,   86,
       75,  360,   84,   76,   98,  355,  106,  103,   87,   79,

       93,   80,   81,   88,   94,   89,  104,  109,   90,  105,
       91,  110,   82,   95,   83,   92,   96,   97,   41,   84,
       44,  354,   42,  106,   41,  348,   44,   93,  346,  111,
       88,   94,   89,  340,  109,   90,  336,   91,  110,  327,
       95,   41,   92,   96,   97,   42,  309,   41,  102,  102,
      102,  102,   48,   48,   48,   48,  111,  287,   41,   41,
       44,   44,   47,   45,   46,   46,   46,   46,   62,   62,
       62,   62,   61,   61,   47,   62,   62,   62,   62,  107,
      108,   41,   41,   48,   48,   48,   48,  117,  118,   47,
      119,  120,  114,   47,   45,   49,   49,   49,   49,  121,

      115,   47,  112,  116,  122,   47,  107,  108,  113,   62,
       62,   62,   62,  124,  117,  118,  125,  119,  120,  114,
       47,  126,  127,  128,  129,  130,  121,  115,  133,  112,
      116,  122,   47,  134,  135,  113,  136,  137,  131,  138,
      124,  139,  140,  125,  144,  283,  145,  148,  126,  127,
      128,  129,  130,  132,  146,  133,  141,  149,  150,  151,
      134,  135,  147,  136,  137,  131,  138,  155,  139,  140,
      142,  144,  143,  145,  148,  152,  156,  157,  158,  160,
      132,  146,  153,  141,  149,  150,  151,  161,  162,  147,
      163,  164,  165,  166,  155,  167,  168,  142,  169,  143,

      170,  171,  152,  156,  157,  158,  160,  172,  173,  153,
      175,  176,  177,  178,  161,  162,  179,  163,  164,  165,
      166,  180,  167,  168,  183,  169,  181,  170,  171,  182,
      184,  185,  186,  187,  172,  173,  188,  175,  176,  177,
      178,  189,  190,  179,  192,  193,  195,  196,  180,  197,
      198,  183,  199,  181,  200,  201,  182,  184,  185,  186,
      187,  202,  203,  188,  204,  205,  206,  207,  189,  190,
      208,  192,  193,  195,  196,  209,  197,  198,  210,  199,
      211,  200,  201,  216,  217,  219,  212,  213,  202,  203,
      221,  204,  205,  206,  207,  214,  222,  208,  223,  224,

      215,  225,  209,  226,  227,  210,  228,  211,  230,  231,
      216,  217,  219,  212,  213,  232,  233,  221,  234,  235,
      236,  239,  214,  222,  240,  223,  224,  215,  225,  237,
      226,  227,  241,  228,  242,  230,  231,  243,  238,  244,
      245,  248,  232,  233,  249,  234,  235,  236,  239,  250,
      246,  240,  251,  252,  253,  254,  237,  247,  255,  241,
      256,  242,  257,  258,  243,  238,  244,  245,  248,  259,
      260,  249,  261,  262,  263,  264,  250,  246,  265,  251,
      252,  253,  254,  266,  247,  255,  267,  256,  268,  257,
      258,  269,  270,  271,  272,  273,  259,  260,  274,  261,

      262,  263,  264,  275,  277,  265,  279,  276,  280,  281,
      266,  282,  284,  267,  285,  268,  286,  288,  269,  270,
      271,  272,  273,  289,  290,  274,  278,  278,  278,  278,
      275,  277,  291,  279,  276,  280,  281,  292,  282,  284,
      293,  285,  294,  286,  288,  295,  296,  297,  298,  299,
      289,  290,  300,  301,  302,  303,  304,  305,  306,  291,
      307,  308,  310,  311,  292,  312,  315,  293,  313,  294,
      316,  317,  295,  296,  297,  298,  299,  314,  318,  300,
      301,  302,  303,  304,  305,  306,  319,  307,  308,  310,
      311,  320,  312,  315,  321,  313,  322,  316,  317,  323,

      324,  325,  326,  328,  329,  318,  278,  278,  278,  278,
      330,  331,  332,  319,  333,  334,  335,  337,  320,  338,
      339,  321,  341,  322,  342,  343,  323,  324,  325,  326,
      328,  329,  344,  345,  347,  349,  350,  330,  331,  332,
      351,  333,  334,  335,  337,  352,  338,  339,  353,  341,
      356,  342,  343,  357,  358,  359,  361,  362,  364,  344,
      345,  347,  349,  350,  365,  366,  367,  351,  368,  369,
      370,  371,  352,  372,  373,  353,  374,  356,  375,  376,
      357,  358,  359,  361,  362,  364,  377,  378,  379,  380,
      382,  365,  366,  367,  383,  368,  369,  370,  371,  384,

      372,  373,  385,  374,  386,  375,  376,  387,  389,  390,
      391,  393,  394,  377,  378,  379,  380,  382,  395,  396,
      397,  383,  398,  399,  400,  401,  384,  402,  403,  385,
      404,  386,  406,  407,  387,  389,  390,  391,  393,  394,
      408,  409,  410,  411,  412,  395,  396,  397,  413,  398,
      399,  400,  401,  414,  402,  403,  415,  404,  416,  406,
      407,  417,  418,  419,  420,  421,  422,  408,  409,  410,
      411,  412,  423,  424,  425,  413,  426,  427,  428,  429,
      414,  430,  431,  415,  432,  416,  433,  434,  417,  418,
      419,  420,  421,  422,  435,  436,  437,  438,  439,  423,

      424,  425,  440,  426,  427,  428,  429,  441,  430,  431,
      442,  432,  444,  433,  434,  445,  446,  447,  448,  449,
      450,  435,  436,  437,  438,  439,  451,  452,  453,  440,
      454,  455,  456,  457,  441,  458,  460,  442,  461,  444,
      462,  463,  445,  446,  447,  448,  449,  450,  464,  465,
      466,  467,  468,  451,  452,  453,  469,  454,  455,  456,
      457,  471,  458,  460,  472,  461,  473,  462,  463,  474,
      477,  478,  479,  480,  481,  464,  465,  466,  467,  468,
      482,  483,  487,  469,  488,  489,  490,  491,  471,  229,
      220,  472,  218,  473,  194,  191,  474,  477,  478,  479,

      480,  481,  174,  101,  159,  154,  123,  482,  483,  487,
      101,  488,  489,  490,  491,   40,   40,   99,   40,   43,
       43,   39,   43,  100,  492,  492,  100,   41,   41,  492,
       41,   44,   44,  492,   44,    3,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,

      492,  492,  492,  492
    } ;

static const flex_int16_t yy_chk[1105] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   18,
       10,   22,    9,  493,    9,  482,   10,   12,   12,   12,
       12,   12,   13,   13,   13,   13,   13,   17,   12,   14,
       14,   14,   14,   13,  470,  470,   18,   17,   22,   14,

       17,  481,   15,   15,   15,   15,   15,  480,    9,    9,
       10,   10,   26,   15,   17,   12,   15,   19,   24,   19,
       13,   20,   19,  463,   17,   20,   14,   17,   23,   20,
       21,   21,   24,   21,   21,   21,   21,   25,   30,   26,
       15,   23,   25,   15,   19,   24,   19,  448,   20,   19,
       27,   21,   20,   27,   27,   23,   20,   28,  426,   24,
      379,   28,   31,   27,   25,   30,   27,   34,   23,   25,
       51,   31,   28,  365,   28,   29,  359,   27,   21,   52,
       27,   27,   53,  351,   28,   29,  325,   29,   28,   31,
       27,  321,   29,   27,   34,  316,   54,   51,   31,   28,

       33,   28,   29,   32,   33,   32,   52,   56,   32,   53,
       32,   57,   29,   33,   29,   32,   33,   33,   40,   29,
       43,  315,   40,   54,   40,  307,   43,   33,  305,   58,
       32,   33,   32,  294,   56,   32,  290,   32,   57,  280,
       33,   42,   32,   33,   33,   42,  260,   42,   50,   50,
       50,   50,   45,   45,   45,   45,   58,  231,   40,   40,
       43,   43,   45,   46,   46,   46,   46,   46,   61,   61,
       61,   61,   47,   47,   46,   47,   47,   47,   47,   55,
       55,   42,   42,   48,   48,   48,   48,   63,   64,   45,
       65,   66,   60,   48,   49,   49,   49,   49,   49,   67,

       60,   46,   59,   60,   68,   49,   55,   55,   59,   62,
       62,   62,   62,   70,   63,   64,   71,   65,   66,   60,
       48,   72,   73,   74,   75,   76,   67,   60,   78,   59,
       60,   68,   49,   79,   80,   59,   81,   82,   77,   83,
       70,   84,   85,   71,   87,  227,   88,   90,   72,   73,
       74,   75,   76,   77,   89,   78,   86,   91,   92,   93,
       79,   80,   89,   81,   82,   77,   83,   96,   84,   85,
       86,   87,   86,   88,   90,   94,   97,   98,   99,  102,
       77,   89,   94,   86,   91,   92,   93,  103,  104,   89,
      105,  106,  107,  108,   96,  109,  110,   86,  111,   86,

      112,  113,   94,   97,   98,   99,  102,  114,  115,   94,
      118,  119,  120,  121,  103,  104,  122,  105,  106,  107,
      108,  123,  109,  110,  125,  111,  124,  112,  113,  124,
      126,  127,  128,  129,  114,  115,  130,  118,  119,  120,
      121,  131,  132,  122,  134,  135,  137,  138,  123,  139,
      140,  125,  141,  124,  142,  143,  124,  126,  127,  128,
      129,  144,  145,  130,  146,  147,  148,  149,  131,  132,
      150,  134,  135,  137,  138,  151,  139,  140,  152,  141,
      153,  142,  143,  155,  156,  158,  154,  154,  144,  145,
      161,  146,  147,  148,  149,  154,  162,  150,  163,  164,

      154,  165,  151,  169,  170,  152,  171,  153,  174,  175,
      155,  156,  158,  154,  154,  176,  177,  161,  178,  179,
      180,  182,  154,  162,  183,  163,  164,  154,  165,  181,
      169,  170,  184,  171,  185,  174,  175,  186,  181,  187,
      188,  190,  176,  177,  191,  178,  179,  180,  182,  192,
      189,  183,  193,  194,  195,  196,  181,  189,  197,  184,
      198,  185,  199,  200,  186,  181,  187,  188,  190,  201,
      202,  191,  203,  204,  205,  206,  192,  189,  208,  193,
      194,  195,  196,  209,  189,  197,  210,  198,  211,  199,
      200,  212,  213,  214,  215,  216,  201,  202,  217,  203,

      204,  205,  206,  218,  219,  208,  221,  218,  222,  225,
      209,  226,  228,  210,  229,  211,  230,  233,  212,  213,
      214,  215,  216,  234,  235,  217,  220,  220,  220,  220,
      218,  219,  236,  221,  218,  222,  225,  237,  226,  228,
      238,  229,  239,  230,  233,  240,  241,  242,  243,  248,
      234,  235,  249,  250,  251,  252,  253,  254,  255,  236,
      257,  258,  261,  262,  237,  263,  265,  238,  264,  239,
      266,  267,  240,  241,  242,  243,  248,  264,  269,  249,
      250,  251,  252,  253,  254,  255,  270,  257,  258,  261,
      262,  271,  263,  265,  272,  264,  273,  266,  267,  274,

      275,  276,  277,  281,  282,  269,  278,  278,  278,  278,
      283,  284,  285,  270,  286,  287,  288,  291,  271,  292,
      293,  272,  296,  273,  300,  302,  274,  275,  276,  277,
      281,  282,  303,  304,  306,  308,  309,  283,  284,  285,
      310,  286,  287,  288,  291,  313,  292,  293,  314,  296,
      317,  300,  302,  318,  319,  320,  322,  323,  327,  303,
      304,  306,  308,  309,  328,  330,  332,  310,  333,  334,
      335,  336,  313,  338,  339,  314,  342,  317,  343,  344,
      318,  319,  320,  322,  323,  327,  346,  348,  349,  350,
      352,  328,  330,  332,  353,  333,  334,  335,  336,  354,

      338,  339,  355,  342,  356,  343,  344,  357,  360,  363,
      364,  366,  367,  346,  348,  349,  350,  352,  368,  369,
      370,  353,  371,  372,  373,  374,  354,  376,  377,  355,
      378,  356,  380,  381,  357,  360,  363,  364,  366,  367,
      382,  383,  384,  385,  387,  368,  369,  370,  388,  371,
      372,  373,  374,  389,  376,  377,  390,  378,  391,  380,
      381,  392,  393,  394,  395,  396,  398,  382,  383,  384,
      385,  387,  401,  402,  403,  388,  405,  406,  407,  409,
      389,  410,  411,  390,  412,  391,  413,  414,  392,  393,
      394,  395,  396,  398,  415,  416,  417,  418,  421,  401,

      402,  403,  422,  405,  406,  407,  409,  423,  410,  411,
      425,  412,  427,  413,  414,  428,  430,  431,  432,  433,
      435,  415,  416,  417,  418,  421,  437,  438,  439,  422,
      440,  442,  444,  446,  423,  447,  449,  425,  451,  427,
      453,  454,  428,  430,  431,  432,  433,  435,  455,  457,
      458,  459,  461,  437,  438,  439,  462,  440,  442,  444,
      446,  464,  447,  449,  467,  451,  468,  453,  454,  469,
      471,  472,  473,  474,  475,  455,  457,  458,  459,  461,
      476,  477,  484,  462,  485,  486,  487,  490,  464,  173,
      159,  467,  157,  468,  136,  133,  469,  471,  472,  473,

      474,  475,  116,  101,  100,   95,   69,  476,  477,  484,
       41,  485,  486,  487,  490,  494,  494,   35,  494,  495,
      495,    8,  495,  496,    3,    0,  496,  497,  497,    0,
      497,  498,  498,    0,  498,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,

      492,  492,  492,  492
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "expt.l"
/*
 *  EXP-T -- A Relativistic Fock-Space Multireference Coupled Cluster Program
 *  Copyright (C) 2018-2024 The EXP-T developers.
 *
 *  This file is part of EXP-T.
 *
 *  EXP-T is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  EXP-T is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with EXP-T.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  E-mail:        exp-t-program@googlegroups.com
 *  Google Groups: https://groups.google.com/d/forum/exp-t-program
 */
#line 25 "expt.l"

#include "lexer.h"

#define MAX_TOKEN_LEN 1024

void inc_col();
int yycol = 0;
int prev_len = -1;

#line 883 "lex.yy.c"
#line 884 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "expt.l"

#line 1103 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 493 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1036 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "expt.l"
{ inc_col(); } /* single-line comments beginning with '#' */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "expt.l"
{ inc_col(); } /* ignore whitespace */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "expt.l"
{ inc_col(); return KEYWORD_TITLE;        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "expt.l"
{ inc_col(); return KEYWORD_PRINT;        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "expt.l"
{ inc_col(); return KEYWORD_SCRATCH_DIR;  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "expt.l"
{ inc_col(); return KEYWORD_DEGEN_THRESH; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "expt.l"
{ inc_col(); return KEYWORD_SECTOR;       }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "expt.l"
{ inc_col(); return KEYWORD_MODEL;        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "expt.l"
{ inc_col(); return KEYWORD_OCC;          }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "expt.l"
{ inc_col(); return KEYWORD_OCC_IRREPS;   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "expt.l"
{ inc_col(); return KEYWORD_ACTIVE;       }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "expt.l"
{ inc_col(); return KEYWORD_NACTP;        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "expt.l"
{ inc_col(); return KEYWORD_NACTH;        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "expt.l"
{ inc_col(); return KEYWORD_HERMIT;       }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "expt.l"
{ inc_col(); return KEYWORD_MSTDM;        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "expt.l"
{ inc_col(); return KEYWORD_NATORB;       }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "expt.l"
{ inc_col(); return KEYWORD_NROOTS;       }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "expt.l"
{ inc_col(); return KEYWORD_ROOTS_CUTOFF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "expt.l"
{ inc_col(); return KEYWORD_MAXITER;      }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "expt.l"
{ inc_col(); return KEYWORD_CONV;         }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "expt.l"
{ inc_col(); return KEYWORD_DIV_THRESH;   }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "expt.l"
{ inc_col(); return KEYWORD_DAMPING;      }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "expt.l"
{ inc_col(); return KEYWORD_DIIS;         }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "expt.l"
{ inc_col(); return KEYWORD_CROP;         }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "expt.l"
{ inc_col(); return KEYWORD_SHIFT_TYPE;   }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "expt.l"
{ inc_col(); return KEYWORD_SHIFT_TYPE;   }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "expt.l"
{ inc_col(); return KEYWORD_SHIFT;        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "expt.l"
{ inc_col(); return KEYWORD_REUSE;        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "expt.l"
{ inc_col(); return KEYWORD_FLUSH;        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "expt.l"
{ inc_col(); return KEYWORD_INTEGRALS;    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "expt.l"
{ inc_col(); return KEYWORD_ONEPROP;      }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "expt.l"
{ inc_col(); return KEYWORD_TWOPROP;      }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "expt.l"
{ inc_col(); return KEYWORD_MEMORY;       }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "expt.l"
{ inc_col(); return KEYWORD_TILESIZE;     }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "expt.l"
{ inc_col(); return KEYWORD_DISK_USAGE;   }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "expt.l"
{ inc_col(); return KEYWORD_COMPRESS;     }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "expt.l"
{ inc_col(); return KEYWORD_COMPRESS_TRIPLES; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "expt.l"
{ inc_col(); return KEYWORD_NTHREADS;     }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "expt.l"
{ inc_col(); return KEYWORD_OPENMP;       }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "expt.l"
{ inc_col(); return KEYWORD_OPENMP_ALGORITHM; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "expt.l"
{ inc_col(); return KEYWORD_CUDA;         }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "expt.l"
{ inc_col(); return KEYWORD_ARITH;        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "expt.l"
{ inc_col(); return KEYWORD_MDPROP;       }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "expt.l"
{ inc_col(); return KEYWORD_TXTPROP;      }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "expt.l"
{ inc_col(); return KEYWORD_END;          }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "expt.l"
{ inc_col(); return KEYWORD_SELECT;       }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "expt.l"
{ inc_col(); return KEYWORD_IH_IMMS;      }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "expt.l"
{ inc_col(); return KEYWORD_IH_IMMS;      }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "expt.l"
{ inc_col(); return KEYWORD_GAUNT;        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "expt.l"
{ inc_col(); return KEYWORD_SKIP;         }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "expt.l"
{ inc_col(); return KEYWORD_INTERFACE;    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "expt.l"
{ inc_col(); return KEYWORD_BREIT;        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "expt.l"
{ inc_col(); return KEYWORD_X2CMMF;       }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "expt.l"
{ inc_col(); return KEYWORD_NEW_SORTING;  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "expt.l"
{ inc_col(); return KEYWORD_RESTRICT_T3;  }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "expt.l"
{ inc_col(); return KEYWORD_SPINOR_LABELS;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "expt.l"
{ inc_col(); return KEYWORD_FLUSH_AMPLITUDES_TXT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "expt.l"
{ inc_col(); return KEYWORD_ANALYT_PROP;  }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "expt.l"
{ inc_col(); return KEYWORD_DENSITY;      }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "expt.l"
{ inc_col(); return KEYWORD_LAMBDA;       }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "expt.l"
{ inc_col(); return KEYWORD_OVERLAP;      }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "expt.l"
{ inc_col(); return KEYWORD_HUGHES_KALDOR_1H2P; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "expt.l"
{ inc_col(); return KEYWORD_HUGHES_KALDOR_2H1P; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "expt.l"
{ inc_col(); return KEYWORD_USE_ORB_ENERGIES; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "expt.l"
{ inc_col(); return KEYWORD_RECALC_ORB_ENERGIES; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 104 "expt.l"
{ inc_col(); return KEYWORD_USE_TT_CCSD;  }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 105 "expt.l"
{ inc_col(); return KEYWORD_TT_SVD_TOL;   }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 106 "expt.l"
{ inc_col(); return KEYWORD_TT_CHOLESKY_TOL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 107 "expt.l"
{ inc_col(); return KEYWORD_TT_MULT_PPPP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 108 "expt.l"
{ inc_col(); return KEYWORD_TT_DIIS;      }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 109 "expt.l"
{ inc_col(); return KEYWORD_TENSOR_TRAINS;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 110 "expt.l"
{ inc_col(); return KEYWORD_GOLDSTONE;    }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 111 "expt.l"
{ inc_col(); return TT_NEQ;               }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 112 "expt.l"
{ inc_col(); return TT_EQ;                }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 113 "expt.l"
{ inc_col(); return TT_QUOTE;             }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 114 "expt.l"
{ inc_col(); return TT_SECTOR;            }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 115 "expt.l"
{ inc_col(); return TT_HYPHEN;            }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 116 "expt.l"
{ inc_col(); return TT_STAR;              }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 117 "expt.l"
{ inc_col(); return TT_ELEC_STATE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 118 "expt.l"
{ inc_col(); return TT_INTEGER;           }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 119 "expt.l"
{ inc_col(); return TT_FLOAT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 120 "expt.l"
{ inc_col(); return TT_WORD;     }
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 121 "expt.l"
{ inc_col(); yylineno++; return END_OF_LINE; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 122 "expt.l"
{ return END_OF_FILE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "expt.l"
ECHO;
	YY_BREAK
#line 1585 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 493 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 493 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 492);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 123 "expt.l"


/* just dummy */
int yywrap() {
   return 1;
}

/**
 * updates the number of the current column
 */
void inc_col()
{
    // update yycol
    if (prev_len == -1) {
        yycol = 0;
    }
    else {
        yycol += prev_len;
    }

    // update prev_len
    if (strcmp(yytext, "\n") == 0) {
        prev_len = -1;
    }
    else {
        prev_len = strlen(yytext);
    }
}


