
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[444] =
    {   0,
       75,   75,   80,   77,    2,   78,    2,   77,   77,    1,
       73,   76,   72,   76,   75,   69,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   79,   79,   77,   68,   77,    0,
       70,    1,    1,   76,   76,   77,   76,   75,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       76,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,    0,   70,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   45,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,    9,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,    0,   71,   77,   77,   77,   77,   77,   20,   24,
       41,   77,   77,   77,   23,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   50,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,    0,   77,
       77,   42,   52,   77,   77,   77,   77,   77,   77,   29,
       49,   77,   77,   77,   77,   77,   77,   77,   77,   77,
        8,   15,   13,   12,   77,   77,   77,   77,   77,   77,
       77,   77,    4,   77,   77,   28,   77,   77,   77,   77,
       27,   77,   77,    3,   77,   77,   77,   77,   77,   77,
       77,   74,   11,   77,   77,   77,   77,   77,   77,   77,
       77,   14,   77,   77,   77,   77,   77,   77,   43,   33,
       16,   77,   17,   77,   77,   77,   39,   77,   77,   77,
       77,   77,    7,   46,   77,   77,   77,   77,   77,   77,

       65,   77,   77,   63,   53,   77,   77,   22,   77,   59,
       77,   77,   77,   77,   48,   77,   77,   47,   19,   77,
       77,   77,   31,   77,   60,   77,   77,   77,   77,   77,
       77,   77,   77,   67,   77,   32,   44,   77,   36,   77,
       77,   77,   77,   77,   77,   77,   77,   38,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   34,   77,   77,
       77,   77,   77,   77,   77,   77,   30,   51,   77,   77,
       77,   64,   77,   77,   77,   25,   77,   77,   77,   77,
       77,   77,   35,   21,   77,   77,   77,   10,   77,   77,
       77,   77,   26,   77,   77,   58,   77,   77,   77,   77,

       54,   77,   55,   77,    5,   77,   77,   77,    6,   77,
       77,   77,   18,   77,   66,   77,   77,   77,   77,   56,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   37,
       77,   77,   77,   40,   77,   77,   77,   77,   61,   62,
       77,   57,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    1,    1,    1,
        1,    8,    9,    1,   10,   11,    1,   12,   13,   14,
       15,   12,   12,   12,   12,   12,   12,   16,    1,    1,
       17,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
        1,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,    1,   43,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,    1,   54,   55,   56,   57,
       58,   59,    1,   60,   61,   62,   63,   64,   65,   66,
       67,   68,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[450] =
    {   0,
        0,    0,  931,    0,  945,  945,    0,  910,   67,   69,
      945,   67,   72,   78,   92,    0,   68,   37,   87,  104,
      122,   44,   84,   97,  113,  133,  140,  139,   80,  141,
      184,  175,  105,  907,    0,  945,    0,    0,  213,  905,
      216,  218,    0,  232,  251,  262,  270,  275,  236,  121,
      143,  142,  158,  223,  174,  187,  183,  269,  268,  255,
      294,  209,  255,  259,  263,  274,  866,  266,  264,  272,
      281,  290,  277,  307,  275,  283,  291,  297,  311,  312,
      313,  310,  330,  314,  313,  327,  322,  323,  325,  324,
      865,  322,  321,  335,  338,  865,  901,  333,  341,  340,

      335,  345,  349,  350,  356,  371,  358,  374,  365,  366,
      374,  862,    0,  368,  373,  375,  380,  380,  385,  383,
      378,  381,  391,  397,  384,  389,  855,  390,  389,  854,
      392,  395,  402,  411,  424,  408,  410,  415,  435,  419,
      433,  433,  425,  428,  437,  432,  443,  429,  431,  271,
      436,  262,    0,  429,  427,  448,  439,  442,    0,    0,
        0,  450,  449,  463,    0,  198,  460,  471,  462,  472,
      482,  478,  484,  491,  475,  480,  479,  485,  485,  494,
      482,  484,  485,  499,  501,  495,  500,  502,  497,  505,
      510,  527,  516,  516,  521,  538,  526,    0,  531,  529,

      542,  539,  530,  536,  535,  536,  540,  543,  568,  551,
      539,    0,    0,  553,  554,  190,  551,  551,  572,  185,
        0,  568,  570,  576,  573,  584,  579,  587,  578,  572,
        0,    0,    0,    0,  596,  585,  583,  600,  586,  589,
      589,  604,    0,  603,  599,    0,  183,  606,  594,  593,
      594,  607,  615,    0,  625,  629,  630,  628,  629,  639,
      639,  651,    0,  181,  635,  646,  636,  632,  639,  641,
      657,    0,  179,  642,  659,  661,  204,  647,    0,    0,
        0,  648,    0,  661,  650,  658,  153,  659,  149,  672,
      673,  669,    0,    0,  655,  670,  148,  670,  678,  678,

        0,  682,  683,    0,    0,  684,  689,    0,  699,    0,
      707,  704,  698,  701,    0,  701,  710,    0,    0,  696,
      699,  712,    0,  717,    0,  705,  702,  708,  143,  713,
      706,  719,  726,    0,  140,    0,    0,  716,  133,  726,
      741,  732,  735,  750,  735,  748,  751,    0,  746,  751,
      758,  130,  746,  761,  761,  752,  767,    0,  755,  757,
      754,  768,  769,  773,  771,  772,    0,    0,  771,  768,
      779,    0,  778,  788,  794,    0,  799,  803,  791,  792,
      798,  798,    0,    0,  807,  813,  811,    0,  805,  133,
      814,  805,    0,  817,  809,    0,  816,  818,  809,  814,

        0,  819,    0,  830,    0,  826,  823,  824,    0,  821,
      834,  847,    0,  840,    0,  847,  855,   98,  842,    0,
      856,  863,   82,  861,  853,  854,  864,  865,  862,    0,
       80,   94,   63,    0,  857,  861,  863,  857,    0,    0,
      862,    0,  945,   73,  924,  928,  932,  936,  940
    } ;

static const flex_int16_t yy_def[450] =
    {   0,
      443,    1,  443,  444,  443,  443,  444,  444,  445,  446,
      443,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  447,  443,  444,  444,  445,  448,
      445,  446,  449,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  447,  448,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  443,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  443,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  443,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,    0,  443,  443,  443,  443,  443,  443
    } ;

static const flex_int16_t yy_nxt[1014] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   15,   15,   15,    4,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,    4,    4,   26,   27,
       28,   29,   30,   31,   32,   33,    4,    4,   34,    4,
        4,   35,   36,    4,   17,   18,   19,   20,   21,   22,
       23,   24,   25,    4,    4,   26,   27,   28,   29,   30,
       31,   32,   33,    4,    4,   34,    4,    4,   40,   53,
       43,   63,   41,   37,   40,  437,   43,   44,   45,   45,
       45,   45,   44,   45,   45,   45,   45,   50,   46,   47,
       47,   47,   47,   46,  427,  428,   53,   51,   63,   46,

       52,   64,   44,   48,   48,   48,   48,  436,   40,   40,
       43,   43,   82,   46,   50,   46,   49,   54,   65,   55,
       46,   57,   56,  435,   51,   58,   46,   52,   64,   59,
       60,   60,   66,   61,   61,   61,   61,   67,   94,   82,
       46,  423,   68,   49,   54,   65,   55,  403,   57,   56,
       69,   62,   58,   70,   71,   99,   59,   74,   78,   66,
      100,   75,   83,   72,   67,   94,   73,  101,   79,   68,
       80,   84,   76,  373,   77,   81,  361,   69,   62,  102,
       70,   71,   99,  359,   74,   78,  354,  100,   75,   83,
       72,  332,  326,   73,  101,   79,  324,   80,   84,   76,

       90,   77,   81,   85,  105,   86,  102,  106,   87,   91,
       88,  107,   92,   93,   40,   89,  318,   40,   41,   43,
       40,   41,  314,   40,  306,   43,  291,   90,  271,  113,
       85,  105,   86,  267,  106,   87,   91,   88,  107,   92,
       93,  218,   89,   47,   47,   47,   47,   98,   98,   98,
       98,  103,  104,   46,   40,   40,  113,   40,   40,   43,
       43,   44,   45,   45,   45,   45,   61,   61,   61,   61,
       60,   60,   46,   61,   61,   61,   61,  209,  103,  104,
       46,   47,   47,   47,   47,   44,   48,   48,   48,   48,
      114,   46,  108,  110,  115,  116,   46,  117,  109,   46,

      119,  111,  120,  121,  112,   61,   61,   61,   61,  122,
      123,  124,  127,  128,  207,  129,  130,  114,   46,  108,
      110,  115,  116,   46,  117,  109,  125,  119,  111,  120,
      121,  112,  131,  132,  133,  134,  122,  123,  124,  127,
      128,  126,  129,  130,  138,  139,  140,  142,  143,  135,
      144,  145,  148,  125,  141,  149,  150,  151,  146,  131,
      132,  133,  134,  136,  153,  137,  154,  155,  126,  156,
      157,  138,  139,  140,  142,  143,  135,  144,  145,  148,
      158,  141,  149,  150,  151,  146,  159,  160,  161,  162,
      136,  153,  137,  154,  155,  163,  156,  157,  164,  165,

      166,  168,  169,  170,  171,  172,  173,  158,  175,  174,
      176,  177,  178,  159,  160,  161,  162,  179,  180,  181,
      183,  184,  163,  186,  187,  164,  165,  166,  168,  169,
      170,  171,  172,  173,  188,  175,  174,  176,  177,  178,
      189,  190,  191,  192,  179,  180,  181,  183,  184,  193,
      186,  187,  194,  195,  196,  197,  198,  199,  200,  201,
      205,  188,  206,  202,  208,  210,  211,  189,  190,  191,
      192,  203,  212,  213,  214,  215,  193,  204,  216,  194,
      195,  196,  197,  198,  199,  200,  201,  205,  217,  206,
      202,  208,  210,  211,  219,  220,  221,  222,  203,  212,

      213,  214,  215,  223,  204,  216,  224,  225,  227,  228,
      229,  230,  231,  232,  235,  217,  226,  236,  233,  237,
      238,  219,  220,  221,  222,  234,  239,  240,  241,  242,
      223,  243,  244,  224,  225,  227,  228,  229,  230,  231,
      232,  235,  245,  226,  236,  233,  237,  238,  246,  247,
      248,  249,  234,  239,  240,  241,  242,  250,  243,  244,
      251,  252,  253,  254,  255,  256,  257,  258,  259,  245,
      260,  261,  263,  264,  265,  246,  247,  248,  249,  262,
      262,  262,  262,  266,  250,  268,  269,  251,  252,  253,
      254,  255,  256,  257,  258,  259,  270,  260,  261,  263,

      264,  265,  272,  273,  274,  275,  276,  277,  278,  279,
      266,  280,  268,  269,  281,  282,  283,  284,  285,  286,
      287,  288,  289,  270,  290,  292,  293,  294,  295,  272,
      273,  274,  275,  276,  277,  278,  279,  296,  280,  297,
      298,  281,  282,  283,  284,  285,  286,  287,  288,  289,
      299,  290,  292,  293,  294,  295,  300,  301,  302,  303,
      304,  305,  262,  262,  262,  262,  297,  298,  307,  308,
      309,  310,  311,  312,  313,  315,  316,  299,  317,  319,
      320,  321,  322,  300,  301,  302,  303,  304,  305,  323,
      325,  327,  328,  329,  330,  307,  308,  309,  310,  311,

      312,  313,  315,  316,  331,  317,  319,  320,  321,  322,
      333,  334,  335,  336,  337,  338,  323,  325,  327,  328,
      329,  330,  339,  340,  341,  342,  343,  344,  345,  346,
      347,  331,  348,  349,  350,  351,  352,  333,  334,  335,
      336,  337,  338,  353,  355,  356,  357,  358,  360,  339,
      340,  341,  342,  343,  344,  345,  346,  347,  362,  348,
      349,  350,  351,  352,  363,  364,  365,  366,  367,  368,
      353,  355,  356,  357,  358,  360,  369,  370,  371,  372,
      374,  375,  376,  377,  378,  362,  379,  380,  381,  382,
      383,  363,  364,  365,  366,  367,  368,  384,  385,  386,

      387,  388,  389,  369,  370,  371,  372,  374,  375,  376,
      377,  378,  390,  379,  380,  381,  382,  383,  391,  392,
      393,  394,  395,  396,  384,  385,  386,  387,  388,  389,
      397,  398,  399,  400,  401,  402,  404,  405,  406,  390,
      407,  408,  409,  410,  411,  391,  392,  393,  394,  395,
      396,  412,  413,  414,  415,  416,  417,  397,  398,  399,
      400,  401,  402,  404,  405,  406,  418,  407,  408,  409,
      410,  411,  419,  420,  421,  422,  424,  425,  412,  413,
      414,  415,  416,  417,  426,  429,  430,  431,  432,  433,
      434,  438,  439,  418,  440,  441,  442,  185,  182,  419,

      420,  421,  422,  424,  425,  167,   97,  152,  147,  118,
       97,  426,  429,  430,  431,  432,  433,  434,  438,  439,
       95,  440,  441,  442,   39,   39,   38,   39,   42,   42,
      443,   42,   96,  443,  443,   96,   40,   40,  443,   40,
       43,   43,  443,   43,    3,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443
    } ;

static const flex_int16_t yy_chk[1014] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   18,
       10,   22,    9,  444,    9,  433,   10,   12,   12,   12,
       12,   12,   13,   13,   13,   13,   13,   17,   12,   14,
       14,   14,   14,   13,  423,  423,   18,   17,   22,   14,

       17,   23,   15,   15,   15,   15,   15,  432,    9,    9,
       10,   10,   29,   15,   17,   12,   15,   19,   24,   19,
       13,   20,   19,  431,   17,   20,   14,   17,   23,   20,
       21,   21,   24,   21,   21,   21,   21,   25,   33,   29,
       15,  418,   25,   15,   19,   24,   19,  390,   20,   19,
       26,   21,   20,   26,   26,   50,   20,   27,   28,   24,
       51,   27,   30,   26,   25,   33,   26,   52,   28,   25,
       28,   30,   27,  352,   27,   28,  339,   26,   21,   53,
       26,   26,   50,  335,   27,   28,  329,   51,   27,   30,
       26,  297,  289,   26,   52,   28,  287,   28,   30,   27,

       32,   27,   28,   31,   55,   31,   53,   56,   31,   32,
       31,   57,   32,   32,   39,   31,  277,   41,   39,   42,
       39,   41,  273,   41,  264,   42,  247,   32,  220,   62,
       31,   55,   31,  216,   56,   31,   32,   31,   57,   32,
       32,  166,   31,   44,   44,   44,   44,   49,   49,   49,
       49,   54,   54,   44,   39,   39,   62,   41,   41,   42,
       42,   45,   45,   45,   45,   45,   60,   60,   60,   60,
       46,   46,   45,   46,   46,   46,   46,  152,   54,   54,
       44,   47,   47,   47,   47,   48,   48,   48,   48,   48,
       63,   47,   58,   59,   64,   65,   48,   66,   58,   45,

       68,   59,   69,   70,   59,   61,   61,   61,   61,   71,
       72,   73,   75,   76,  150,   77,   78,   63,   47,   58,
       59,   64,   65,   48,   66,   58,   74,   68,   59,   69,
       70,   59,   79,   80,   81,   82,   71,   72,   73,   75,
       76,   74,   77,   78,   84,   85,   86,   87,   88,   83,
       89,   90,   92,   74,   86,   93,   94,   95,   90,   79,
       80,   81,   82,   83,   98,   83,   99,  100,   74,  101,
      102,   84,   85,   86,   87,   88,   83,   89,   90,   92,
      103,   86,   93,   94,   95,   90,  104,  105,  106,  107,
       83,   98,   83,   99,  100,  108,  101,  102,  109,  110,

      111,  114,  115,  116,  117,  118,  119,  103,  120,  119,
      121,  122,  123,  104,  105,  106,  107,  124,  125,  126,
      128,  129,  108,  131,  132,  109,  110,  111,  114,  115,
      116,  117,  118,  119,  133,  120,  119,  121,  122,  123,
      134,  135,  136,  137,  124,  125,  126,  128,  129,  138,
      131,  132,  139,  140,  141,  142,  143,  144,  145,  146,
      148,  133,  149,  147,  151,  154,  155,  134,  135,  136,
      137,  147,  156,  157,  158,  162,  138,  147,  163,  139,
      140,  141,  142,  143,  144,  145,  146,  148,  164,  149,
      147,  151,  154,  155,  167,  168,  169,  170,  147,  156,

      157,  158,  162,  171,  147,  163,  172,  173,  174,  175,
      176,  177,  178,  179,  181,  164,  173,  182,  180,  183,
      184,  167,  168,  169,  170,  180,  185,  186,  187,  188,
      171,  189,  190,  172,  173,  174,  175,  176,  177,  178,
      179,  181,  191,  173,  182,  180,  183,  184,  192,  193,
      194,  195,  180,  185,  186,  187,  188,  196,  189,  190,
      197,  199,  200,  201,  202,  203,  204,  205,  206,  191,
      207,  208,  210,  211,  214,  192,  193,  194,  195,  209,
      209,  209,  209,  215,  196,  217,  218,  197,  199,  200,
      201,  202,  203,  204,  205,  206,  219,  207,  208,  210,

      211,  214,  222,  223,  224,  225,  226,  227,  228,  229,
      215,  230,  217,  218,  235,  236,  237,  238,  239,  240,
      241,  242,  244,  219,  245,  248,  249,  250,  251,  222,
      223,  224,  225,  226,  227,  228,  229,  251,  230,  252,
      253,  235,  236,  237,  238,  239,  240,  241,  242,  244,
      255,  245,  248,  249,  250,  251,  256,  257,  258,  259,
      260,  261,  262,  262,  262,  262,  252,  253,  265,  266,
      267,  268,  269,  270,  271,  274,  275,  255,  276,  278,
      282,  284,  285,  256,  257,  258,  259,  260,  261,  286,
      288,  290,  291,  292,  295,  265,  266,  267,  268,  269,

      270,  271,  274,  275,  296,  276,  278,  282,  284,  285,
      298,  299,  300,  302,  303,  306,  286,  288,  290,  291,
      292,  295,  307,  309,  311,  312,  313,  314,  316,  317,
      320,  296,  321,  322,  324,  326,  327,  298,  299,  300,
      302,  303,  306,  328,  330,  331,  332,  333,  338,  307,
      309,  311,  312,  313,  314,  316,  317,  320,  340,  321,
      322,  324,  326,  327,  341,  342,  343,  344,  345,  346,
      328,  330,  331,  332,  333,  338,  347,  349,  350,  351,
      353,  354,  355,  356,  357,  340,  359,  360,  361,  362,
      363,  341,  342,  343,  344,  345,  346,  364,  365,  366,

      369,  370,  371,  347,  349,  350,  351,  353,  354,  355,
      356,  357,  373,  359,  360,  361,  362,  363,  374,  375,
      377,  378,  379,  380,  364,  365,  366,  369,  370,  371,
      381,  382,  385,  386,  387,  389,  391,  392,  394,  373,
      395,  397,  398,  399,  400,  374,  375,  377,  378,  379,
      380,  402,  404,  406,  407,  408,  410,  381,  382,  385,
      386,  387,  389,  391,  392,  394,  411,  395,  397,  398,
      399,  400,  412,  414,  416,  417,  419,  421,  402,  404,
      406,  407,  408,  410,  422,  424,  425,  426,  427,  428,
      429,  435,  436,  411,  437,  438,  441,  130,  127,  412,

      414,  416,  417,  419,  421,  112,   97,   96,   91,   67,
       40,  422,  424,  425,  426,  427,  428,  429,  435,  436,
       34,  437,  438,  441,  445,  445,    8,  445,  446,  446,
        3,  446,  447,    0,    0,  447,  448,  448,    0,  448,
      449,  449,    0,  449,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "expt.l"
/*
 *  EXP-T -- A Relativistic Fock-Space Multireference Coupled Cluster Program
 *  Copyright (C) 2018-2024 The EXP-T developers.
 *
 *  This file is part of EXP-T.
 *
 *  EXP-T is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  EXP-T is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with EXP-T.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  E-mail:        exp-t-program@googlegroups.com
 *  Google Groups: https://groups.google.com/d/forum/exp-t-program
 */
#line 25 "expt.l"

#include "lexer.h"

#define MAX_TOKEN_LEN 1024

void inc_col();
int yycol = 0;
int prev_len = -1;

#line 845 "lex.yy.c"
#line 846 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "expt.l"

#line 1065 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 444 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 945 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "expt.l"
{ inc_col(); } /* single-line comments beginning with '#' */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "expt.l"
{ inc_col(); } /* ignore whitespace */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "expt.l"
{ inc_col(); return KEYWORD_TITLE;        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "expt.l"
{ inc_col(); return KEYWORD_PRINT;        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "expt.l"
{ inc_col(); return KEYWORD_SCRATCH_DIR;  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "expt.l"
{ inc_col(); return KEYWORD_DEGEN_THRESH; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "expt.l"
{ inc_col(); return KEYWORD_SECTOR;       }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "expt.l"
{ inc_col(); return KEYWORD_MODEL;        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "expt.l"
{ inc_col(); return KEYWORD_OCC;          }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "expt.l"
{ inc_col(); return KEYWORD_OCC_IRREPS;   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "expt.l"
{ inc_col(); return KEYWORD_ACTIVE;       }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "expt.l"
{ inc_col(); return KEYWORD_NACTP;        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "expt.l"
{ inc_col(); return KEYWORD_NACTH;        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "expt.l"
{ inc_col(); return KEYWORD_HERMIT;       }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "expt.l"
{ inc_col(); return KEYWORD_MSTDM;        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "expt.l"
{ inc_col(); return KEYWORD_NATORB;       }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "expt.l"
{ inc_col(); return KEYWORD_NROOTS;       }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "expt.l"
{ inc_col(); return KEYWORD_ROOTS_CUTOFF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "expt.l"
{ inc_col(); return KEYWORD_MAXITER;      }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "expt.l"
{ inc_col(); return KEYWORD_CONV;         }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "expt.l"
{ inc_col(); return KEYWORD_DIV_THRESH;   }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "expt.l"
{ inc_col(); return KEYWORD_DAMPING;      }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "expt.l"
{ inc_col(); return KEYWORD_DIIS;         }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "expt.l"
{ inc_col(); return KEYWORD_CROP;         }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "expt.l"
{ inc_col(); return KEYWORD_SHIFT_TYPE;   }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "expt.l"
{ inc_col(); return KEYWORD_SHIFT_TYPE;   }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "expt.l"
{ inc_col(); return KEYWORD_SHIFT;        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "expt.l"
{ inc_col(); return KEYWORD_REUSE;        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "expt.l"
{ inc_col(); return KEYWORD_FLUSH;        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "expt.l"
{ inc_col(); return KEYWORD_INTEGRALS;    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "expt.l"
{ inc_col(); return KEYWORD_ONEPROP;      }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "expt.l"
{ inc_col(); return KEYWORD_TWOPROP;      }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "expt.l"
{ inc_col(); return KEYWORD_MEMORY;       }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "expt.l"
{ inc_col(); return KEYWORD_TILESIZE;     }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "expt.l"
{ inc_col(); return KEYWORD_DISK_USAGE;   }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "expt.l"
{ inc_col(); return KEYWORD_COMPRESS;     }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "expt.l"
{ inc_col(); return KEYWORD_COMPRESS_TRIPLES; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "expt.l"
{ inc_col(); return KEYWORD_NTHREADS;     }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "expt.l"
{ inc_col(); return KEYWORD_OPENMP;       }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "expt.l"
{ inc_col(); return KEYWORD_OPENMP_ALGORITHM; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "expt.l"
{ inc_col(); return KEYWORD_CUDA;         }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "expt.l"
{ inc_col(); return KEYWORD_ARITH;        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "expt.l"
{ inc_col(); return KEYWORD_MDPROP;       }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "expt.l"
{ inc_col(); return KEYWORD_TXTPROP;      }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "expt.l"
{ inc_col(); return KEYWORD_END;          }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "expt.l"
{ inc_col(); return KEYWORD_SELECT;       }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "expt.l"
{ inc_col(); return KEYWORD_IH_IMMS;      }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "expt.l"
{ inc_col(); return KEYWORD_IH_IMMS;      }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "expt.l"
{ inc_col(); return KEYWORD_GAUNT;        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "expt.l"
{ inc_col(); return KEYWORD_SKIP;         }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "expt.l"
{ inc_col(); return KEYWORD_INTERFACE;    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "expt.l"
{ inc_col(); return KEYWORD_BREIT;        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "expt.l"
{ inc_col(); return KEYWORD_X2CMMF;       }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "expt.l"
{ inc_col(); return KEYWORD_NEW_SORTING;  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "expt.l"
{ inc_col(); return KEYWORD_RESTRICT_T3;  }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "expt.l"
{ inc_col(); return KEYWORD_SPINOR_LABELS;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "expt.l"
{ inc_col(); return KEYWORD_FLUSH_AMPLITUDES_TXT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "expt.l"
{ inc_col(); return KEYWORD_ANALYT_PROP;  }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "expt.l"
{ inc_col(); return KEYWORD_DENSITY;      }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "expt.l"
{ inc_col(); return KEYWORD_OVERLAP;      }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "expt.l"
{ inc_col(); return KEYWORD_HUGHES_KALDOR_1H2P; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "expt.l"
{ inc_col(); return KEYWORD_HUGHES_KALDOR_2H1P; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "expt.l"
{ inc_col(); return KEYWORD_USE_ORB_ENERGIES; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "expt.l"
{ inc_col(); return KEYWORD_RECALC_ORB_ENERGIES; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "expt.l"
{ inc_col(); return KEYWORD_TT_TOL;       }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 104 "expt.l"
{ inc_col(); return KEYWORD_TT_MULT_PPPP; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 105 "expt.l"
{ inc_col(); return KEYWORD_TT_DIIS;      }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 106 "expt.l"
{ inc_col(); return TT_NEQ;               }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 107 "expt.l"
{ inc_col(); return TT_EQ;                }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 108 "expt.l"
{ inc_col(); return TT_QUOTE;             }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 109 "expt.l"
{ inc_col(); return TT_SECTOR;            }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 110 "expt.l"
{ inc_col(); return TT_HYPHEN;            }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 111 "expt.l"
{ inc_col(); return TT_STAR;              }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 112 "expt.l"
{ inc_col(); return TT_ELEC_STATE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 113 "expt.l"
{ inc_col(); return TT_INTEGER;           }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 114 "expt.l"
{ inc_col(); return TT_FLOAT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 115 "expt.l"
{ inc_col(); return TT_WORD;     }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 116 "expt.l"
{ inc_col(); yylineno++; return END_OF_LINE; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 117 "expt.l"
{ return END_OF_FILE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 118 "expt.l"
ECHO;
	YY_BREAK
#line 1522 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 444 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 444 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 443);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 118 "expt.l"


/* just dummy */
int yywrap() {
   return 1;
}

/**
 * updates the number of the current column
 */
void inc_col()
{
    // update yycol
    if (prev_len == -1) {
        yycol = 0;
    }
    else {
        yycol += prev_len;
    }

    // update prev_len
    if (strcmp(yytext, "\n") == 0) {
        prev_len = -1;
    }
    else {
        prev_len = strlen(yytext);
    }
}


